version: "3"

services:
  php:
    build: images/php
    volumes:
      - ..:/usr/app
      - ./images/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    working_dir: /usr/app
    user: ${HOST_USER_UID}:${HOST_USER_GID}
